[workspace]

members = [
	"json_dynamic",
	"json_static",
	"postgresql_example",
	"redis_example",
	"sqlite_example",
	"use_env_logger",
	"use_lazy_static",
	"use_rand",
	"use_structopt",
	"strsplit",
	"toml_dynamic",
	"toml_static",
	"transformer",
	"xml_example",
]
