[package]
name = "toml_dynamic"
version = "0.1.0"
authors = ["abdullah <44318011+fx2y@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"